on: [push, pull_request]
name: Build
env:
  GO111MODULE: on
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.18.x, 1.19.x]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'
    - name: Install Kotlin
      uses: fwilhe2/setup-kotlin@main
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Info Script
      run: ./info.sh
    - name: Test
      run: go test ./...

  test-cache:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'
    - name: Install Kotlin
      uses: fwilhe2/setup-kotlin@main
      with:
        go-version: 1.18.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Info Script
      run: ./info.sh
    - uses: actions/cache@v2
      with:
        path: |
          ~/go/pkg/mod              # Module download cache
          ~/.cache/go-build         # Build cache (Linux)
          ~/Library/Caches/go-build # Build cache (Mac)
          '%LocalAppData%\go-build' # Build cache (Windows)
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Test
      run: go test ./...
